"""Detection signals for Provenance Guard.

Signal 1: Groq LLM classification (semantic / holistic).
Signal 2: stylometric heuristics (structural).
"""
import json
import os
import re

from groq import Groq

MODEL = "llama-3.3-70b-versatile"

_SYSTEM = (
    "You are a careful AI-content detector. Judge whether the given text was "
    "written by a human or generated by an AI language model. Respond ONLY with "
    'JSON: {"ai_likelihood": <float 0.0-1.0>, "reason": "<short phrase>"}.\n'
    "Calibrate honestly:\n"
    "- 0.0-0.3: clearly human (personal, irregular, casual, or distinctive).\n"
    "- 0.4-0.6: genuinely UNSURE - use this range whenever you are not "
    "confident either way.\n"
    "- 0.7-1.0: clearly AI (generic, evenly structured, hedging boilerplate).\n"
    "Formal, polished, or non-native human writing is NOT by itself proof of "
    "AI. Do not score formality alone above 0.6. A false accusation against a "
    "human writer is worse than missing an AI text, so when in doubt, stay near "
    "the middle."
)


def llm_signal(text):
    """Return Signal 1 as a dict: {'llm_score': float 0-1, 'reason': str}.

    llm_score is the model's estimated AI-likelihood. Raises if the API key
    is missing so failures are loud, not silent.
    """
    client = Groq(api_key=os.environ["GROQ_API_KEY"])
    resp = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": _SYSTEM},
            {"role": "user", "content": text},
        ],
        temperature=0,
        response_format={"type": "json_object"},
    )
    data = json.loads(resp.choices[0].message.content)
    score = float(data.get("ai_likelihood", 0.5))
    score = max(0.0, min(1.0, score))  # clamp to 0-1
    return {"llm_score": score, "reason": data.get("reason", "")}


def _clamp(x):
    return max(0.0, min(1.0, x))


def style_signal(text):
    """Signal 2: stylometric heuristics. Returns a dict with the combined
    'style_score' (0-1 AI-likelihood) and the 3 raw metrics.

    Three structural metrics, each pointing toward AI when text looks uniform:
      - sentence-length variation (coefficient of variation): low = uniform = AI
      - type-token ratio (vocabulary diversity): high+polished leans AI
      - punctuation density (commas/semicolons per sentence): high = AI-like
    AI writing tends to be uniform and evenly punctuated; human writing varies.
    """
    sentences = [s for s in re.split(r"[.!?]+", text) if s.strip()]
    words = re.findall(r"[a-zA-Z']+", text.lower())
    if len(words) < 5 or len(sentences) < 1:
        # Too little text for reliable stats -> stay neutral.
        return {
            "style_score": 0.5,
            "len_cv": None,
            "type_token_ratio": None,
            "punct_density": None,
            "note": "text too short for reliable stylometrics",
        }

    # 1. Sentence-length variation (coefficient of variation).
    lengths = [len(re.findall(r"[a-zA-Z']+", s)) for s in sentences]
    mean_len = sum(lengths) / len(lengths)
    if len(lengths) > 1 and mean_len > 0:
        var = sum((x - mean_len) ** 2 for x in lengths) / len(lengths)
        cv = (var ** 0.5) / mean_len
    else:
        cv = 0.0
    # cv >= 0.6 -> human (0.0), cv <= 0.15 -> AI (1.0)
    uniformity = _clamp((0.6 - cv) / (0.6 - 0.15))

    # 2. Type-token ratio (unique / total words).
    ttr = len(set(words)) / len(words)
    # ttr <= 0.4 -> human-casual (0.0), ttr >= 0.75 -> polished/AI (1.0)
    diversity = _clamp((ttr - 0.4) / (0.75 - 0.4))

    # 3. Punctuation density (commas + semicolons per sentence).
    punct = text.count(",") + text.count(";")
    density = punct / len(sentences)
    # 0 per sentence -> human (0.0), >= 2 per sentence -> AI (1.0)
    punct_score = _clamp(density / 2.0)

    style_score = round((uniformity + diversity + punct_score) / 3.0, 3)
    return {
        "style_score": style_score,
        "len_cv": round(cv, 3),
        "type_token_ratio": round(ttr, 3),
        "punct_density": round(density, 3),
    }


if __name__ == "__main__":
    # Quick manual test: run `python signals.py`
    from dotenv import load_dotenv

    load_dotenv()
    samples = [
        "ok so i finally tried that ramen place and honestly? underwhelming.",
        "Artificial intelligence represents a transformative paradigm shift. "
        "It is important to note the ethical implications stakeholders must weigh.",
    ]
    for s in samples:
        print(s[:40], "-> llm", llm_signal(s), "| style", style_signal(s))
